const colorMap = {
    'white': 'white', 'branco': 'white', 'blanco': 'white', 'ivory': 'white', 'marfim': 'white', 'marfil': 'white',
    'black': 'black', 'preto': 'black', 'negro': 'black', 'ebony': 'black', 'ébano': 'black',
    'blue': 'blue', 'azul': 'blue', 'navy': 'navy', 'azul-marinho': 'navy', 'azul marino': 'navy', 'cyan': 'cyan', 'ciano': 'cyan', 'turquesa': 'turquoise', 'turquoise': 'turquoise',
    'green': 'green', 'verde': 'green', 'lime': 'lime', 'lima': 'lime', 'emerald': 'emerald', 'esmeralda': 'emerald', 'olive': 'olive', 'oliva': 'olive',
    'red': 'red', 'vermelho': 'red', 'rojo': 'red', 'crimson': 'red', 'carmesim': 'red', 'escarlata': 'red', 'vermilion': 'red', 'vermilhão': 'red', 'carmim': 'red',
    'pink': 'pink', 'rosa': 'pink', 'rose': 'pink', 'rosado': 'pink', 'coral': 'coral', 'coral': 'coral',
    'yellow': 'yellow', 'amarelo': 'yellow', 'amarillo': 'yellow', 'gold': 'gold', 'dourado': 'gold', 'dorado': 'gold', 'amber': 'amber', 'âmbar': 'amber', 'ámbar': 'amber',
    'purple': 'purple', 'roxo': 'purple', 'púrpura': 'purple', 'violet': 'purple', 'violeta': 'purple', 'lilac': 'lilac', 'lilás': 'lilac', 'lila': 'lilac',
    'mauve': 'mauve', 'malva': 'mauve', 'lavender': 'lavender', 'lavanda': 'lavender',
    'gray': 'gray', 'cinza': 'gray', 'gris': 'gray', 'grey': 'gray', 'silver': 'silver', 'prata': 'silver', 'plateado': 'silver',
    'brown': 'brown', 'marrom': 'brown', 'marrón': 'brown', 'chocolate': 'brown', 'chocolate': 'brown', 'castanho': 'brown',
    'beige': 'beige', 'bege': 'beige', 'creme': 'beige', 'crema': 'beige', 'taupe': 'taupe', 'cinza-bege': 'taupe', 'gris pardo': 'taupe',
    'orange': 'orange', 'laranja': 'orange', 'naranja': 'orange', 'tangerine': 'orange', 'tangerina': 'orange',
    'starlight': 'starlight', 'estrela': 'starlight', 'estrella': 'starlight',
    'midnight': 'midnight', 'meia-noite': 'midnight', 'medianoche': 'midnight',
    'space gray': 'space gray', 'cinza espacial': 'space gray', 'gris espacial': 'space gray',
    'rose gold': 'rose gold', 'ouro rosé': 'rose gold', 'oro rosa': 'rose gold',
    'white star': 'white star', 'estrela branca': 'white star', 'estrella blanca': 'white star',
    'black night': 'black night', 'noite preta': 'black night', 'noche negra': 'black night',
    'multicolor': 'multicolor', 'multicor': 'multicolor', 'multicolour': 'multicolor', 'multicolores': 'multicolor',
    'bronze': 'bronze', 'bronze': 'bronze', 'bronce': 'bronze',
    'teal': 'teal', 'petróleo': 'teal', 'turquesa escura': 'teal',
    'magenta': 'magenta', 'magenta': 'magenta', 'fúcsia': 'magenta',
    'charcoal': 'charcoal', 'carvão': 'charcoal', 'carbón': 'charcoal',
    'mint': 'mint', 'menta': 'mint', 'hierbabuena': 'mint',
    'peach': 'peach', 'pêssego': 'peach', 'melocotón': 'peach',
    'cream': 'cream', 'creme': 'cream', 'crema': 'cream',
    'sand': 'sand', 'areia': 'sand', 'arena': 'sand',
    'graphite': 'graphite', 'grafite': 'graphite', 'grafito': 'graphite',
    'jade': 'jade', 'jade': 'jade', 'jade': 'jade',
    'sky blue': 'sky blue', 'azul céu': 'sky blue', 'azul celeste': 'sky blue',
    'wine': 'wine', 'vinho': 'wine', 'vino': 'wine'
};

module.exports = { colorMap };